## General config
skip_global_compinit=1

export PATH=$ZSH_CUSTOM/plugins/git-fuzzy/bin:$HOME/bin:$HOME/.local/bin:$HOME/npm/bin:$HOME/.cargo/bin:$PATH
export EDITOR='nvim'
export VIRTUAL_ENV_DISABLE_PROMPT=
export LANG=en_US.UTF-8

## Zsh
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="spaceship"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"

##
## Prompt
##
SPACESHIP_PROMPT_ORDER=(
    user
    host
    dir
    kubectl_context
    git
    venv
    line_sep
    char
)

SPACESHIP_RPROMPT_ORDER=(
    jobs
    exit_code
)

#### Disable some features
export SPACESHIP_PACKAGE_SHOW=false
export SPACESHIP_NODE_SHOW=false
export SPACESHIP_DOCKER_SHOW=false

#### Char
export SPACESHIP_CHAR_SYMBOL=""
export SPACESHIP_CHAR_SUFFIX="  "

#### Venv
export SPACESHIP_VENV_SUFFIX="%F{226}) "
export SPACESHIP_VENV_PREFIX="%F{226}(venv: "
export SPACESHIP_VENV_COLOR=226

#### Dir
export SPACESHIP_DIR_TRUNC_REPO=false
export SPACESHIP_DIR_TRUNC=0

#### k8s
export SPACESHIP_KUBECONTEXT_COLOR=033
export SPACESHIP_KUBECONTEXT_SUFFIX=" %F{033}\u2388 "
export SPACESHIP_KUBECONTEXT_PREFIX="%F{033}\u2388 "

#### Git
export SPACESHIP_GIT_PREFIX=

#### Exit code
export SPACESHIP_EXIT_CODE_SHOW=true

#### Jobs
export SPACESHIP_JOBS_SYMBOL=""

##
## Oh my ZSH Plugins
###
plugins=(
  ansible
  command-not-found
  docker
  gcloud
  git
  httpie
  kubectl
  pip
  python
  sudo
  vagrant
  vi-mode
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

setopt inc_append_history
setopt share_history

# Custom functions
function upgrade_python_packages() {
    pip install --upgrade --user pip
    pip-compile --upgrade $HOME/.python/packages.in --output-file $HOME/.python/packages.txt
    pip install --user -r $HOME/.python/packages.txt
}

# Aliases

## Shortcuts
alias upgrade="sudo pacman -Syu && omz update && upgrade_python_packages"
alias download_mp3="youtube-dl -x --audio-format mp3 --audio-quality 0"

## k8s
alias start_minikube='minikube start --driver=docker --kubernetes-version=v1.19.0 --cpus=4 --memory=12gb --feature-gates="LocalStorageCapacityIsolation=false"'
alias kadm="kubectl -n kube-system "
alias k="kubectl"
alias kc="kubectx"

## Commands
alias cat="bat"
alias ls="exa -g -H -h --git"
alias find="fd"
alias ps="procs"
alias l="ls -l"
alias la="l -a"
alias ld="l -D"
alias vim="nvim"
alias vi="nvim"
alias t="exa --tree"
alias sudo="sudo "

## git
alias gd="git fuzzy diff"
alias gs="git fuzzy status"
alias gl="git pull"

# i3 tmux
unset I3SOCK

# Rust
source ~/.cargo/env

# FZF
fz() {
  local z_path
  z_path=$(z -l | fzf-tmux -d '100%' | awk '{print $2}')
  cd $(echo "$z_path")
}
zle     -N   fz
bindkey '^F' fz

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

export FZF_DEFAULT_OPTS='--border --height=60%'
export _Z_EXCLUDE_DIRS=".cache|.git|.venv|node_modules"
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow -g '!.git' -g '!node_modules' -g '!.venv' 2>/dev/null"

# SSH Agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# X
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
