- name: Install gpu monitoring tools
  community.general.pacman:
    name:
      - intel-gpu-tools
      - nvtop
    state: latest
  become: true

- name: Install Vulkan for intel gpu
  community.general.pacman:
    name:
      - vulkan-icd-loader
      - vulkan-intel
      - vulkan-tools
      - vulkan-validation-layers
    state: latest
  become: true

- name: Download wgsl-analyer
  ansible.builtin.get_url:
    url: https://github.com/wgsl-analyzer/wgsl-analyzer/releases/latest/download/wgsl-analyzer-x86_64-unknown-linux-musl.gz
    dest: /tmp/
    mode: "0644"

- name: Unarchive wgsl-analyer # noqa no-changed-when
  ansible.builtin.shell: |
    gzip -d /tmp/wgsl-analyzer-x86_64-unknown-linux-musl.gz
    mv /tmp/wgsl-analyzer-x86_64-unknown-linux-musl ~/.local/bin/wgsl-analyzer
    chmod +x ~/.local/bin/wgsl-analyzer
