- name: Install python tools
  community.general.pacman:
    name:
      - uv
      - ruff
      - ty
    state: latest
  become: true

- name: Create $HOME/.python venv
  ansible.builtin.command: |
    uv venv $HOME/.python
  changed_when: false

- name: Install python packages
  ansible.builtin.command: |
    uv pip install \
      ipython \
      pdbpp \
      pgcli \
      pynvim

  environment:
    VIRTUAL_ENV: "{{ ansible_env.HOME }}/.python"
  changed_when: false

#
# pdbpp
#
- name: Copy pdbpp config
  ansible.builtin.copy:
    src: python/pdbrc.py
    dest: $HOME/.pdbrc.py
    mode: "0644"
