- name: Install yay
  ansible.builtin.unarchive:
    src: https://github.com/Jguer/yay/releases/download/v12.5.0/yay_12.5.0_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: true
    include: yay_12.5.0_x86_64/yay
    extra_opts:
      - --strip-components=1
    mode: "0755"
  become: true

- name: Create config dir
  ansible.builtin.file:
    path: $HOME/.config/yay
    state: directory
    mode: "0755"

- name: Copy yay config file
  ansible.builtin.copy:
    src: config/yay/config.json
    dest: ~/.config/yay/config.json
    mode: "0644"
