##
## Zsh
##

export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

setopt inc_append_history
setopt share_history

DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"

##
## General config
##

skip_global_compinit=1

export PATH=$ZSH_CUSTOM/plugins/git-fuzzy/bin:$HOME/.local/bin:$HOME/.npm-packages/bin:$HOME/.cargo/bin:$HOME/.python/bin:$PATH
export EDITOR='nvim'
export VIRTUAL_ENV_DISABLE_PROMPT=
export LANG=en_US.UTF-8
export MANPAGER='nvim +Man!'
export MANWIDTH=999

##
## Prompt
##

export STARSHIP_CONFIG=~/.config/starship/config.toml
eval "$(starship init zsh)"

##
## Oh my ZSH Plugins
##

plugins=(
  ansible
  command-not-found
  docker
  gcloud
  git
  httpie
  kubectl
  pip
  python
  vi-mode
  fzf-tab
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

export VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true

source $ZSH/oh-my-zsh.sh

enable-fzf-tab
zstyle ':fzf-tab:*' fzf-pad 4

##
## Aliases
##

## Shortcuts
alias upgrade="yay ; omz update ; rustup update"
alias j="just"

## k8s
alias start_minikube='minikube start -p dev --driver=docker --kubernetes-version=v1.25.13 --cpus=4 --memory=12gb'
alias delete_minikube='minikube delete -p dev'
alias stop_minikube="minikube stop -p dev"
alias kadm="kubectl -n kube-system "
alias k="kubectl"
alias kc="kubectx"
alias skaffold="source <(minikube docker-env -p dev) && skaffold"

## Commands
alias cat="bat"
alias ls="eza -g -H -h --git"
alias find="fd"
alias ps="procs"
alias l="ls -l"
alias la="l -a"
alias ld="l -D"
alias vim="nvim"
alias vi="nvim"
alias t="eza --tree --git-ignore"
alias sudo="sudo "
alias pdf="zathura"
alias diff="difft"

## git
alias gd="git fuzzy diff"
alias gs="git fuzzy status"
alias gl="git pull"

##
## ESP
##
if [ -f $HOME/.espup/export-esp.sh ]; then
    source $HOME/.espup/export-esp.sh
fi

##
## i3 tmux
##

unset I3SOCK

##
## gcloud
##

if [ -f $HOME/gcloud/google-cloud-sdk/path.zsh.inc ]; then
    source $HOME/gcloud/google-cloud-sdk/path.zsh.inc
fi

if [ -f $HOME/gcloud/google-cloud-sdk/completion.zsh.inc ]; then
    source $HOME/gcloud/google-cloud-sdk/completion.zsh.inc
fi

##
## Pyenv
##

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

##
## FZF
##

export _ZO_EXCLUDE_DIRS=".cache|.git|.venv|node_modules"
export FZF_DEFAULT_OPTS='--border --height=60%'
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow -g '!.git' -g '!node_modules' -g '!.venv' 2>/dev/null"

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

##
## Zoxide
##
eval "$(zoxide init zsh)"

_zi () {
    zi
}

zle     -N   _zi
bindkey '^F' _zi

##
## SSH Agent
##
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

##
## X
##
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
