## Zsh
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"

## General config
skip_global_compinit=1

export PATH=$HOME/.pyenv/shims:$ZSH_CUSTOM/plugins/git-fuzzy/bin:$HOME/.local/bin:$HOME/.npm-packages/bin:$HOME/.cargo/bin:$PATH
export EDITOR='nvim'
export VIRTUAL_ENV_DISABLE_PROMPT=
export LANG=en_US.UTF-8
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

##
## Prompt
##
export STARSHIP_CONFIG=~/.config/starship/config.toml
eval "$(starship init zsh)"

##
## Oh my ZSH Plugins
###
plugins=(
  ansible
  command-not-found
  docker
  fzf-tab
  gcloud
  git
  httpie
  kubectl
  pip
  pyenv
  python
  sudo
  vagrant
  vi-mode
  z
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
setopt inc_append_history
setopt share_history

# Custom functions
function upgrade_python_packages() {
    pip install --upgrade --user pip
    pip-compile --upgrade $HOME/.python/packages.in --output-file $HOME/.python/packages.txt --resolver=backtracking
    pip install --user -r $HOME/.python/packages.txt
}

# Aliases

## Shortcuts
alias upgrade="yay ; omz update ; upgrade_python_packages ; rustup update"

## k8s
alias start_minikube='minikube start -p dev --driver=docker --kubernetes-version=v1.22.17 --cpus=4 --memory=12gb --feature-gates="LocalStorageCapacityIsolation=false"'
alias delete_minikube='minikube delete -p dev'
alias kadm="kubectl -n kube-system "
alias k="kubectl"
alias kc="kubectx"
alias skaffold="source <(minikube docker-env -p minikube) && skaffold"

## Commands
alias cat="bat"
alias ls="exa -g -H -h --git"
alias find="fd"
alias ps="procs"
alias l="ls -l"
alias la="l -a"
alias ld="l -D"
alias vim="nvim"
alias vi="nvim"
alias t="exa --tree"
alias sudo="sudo "
alias pdf="zathura"
alias diff="difft"

## git
alias gd="git fuzzy diff"
alias gs="git fuzzy status"
alias gl="git pull"

## ESP
alias get_idf="source $HOME/.esp/export.sh"

# i3 tmux
unset I3SOCK

# Rust
source ~/.cargo/env

# FZF
fz() {
  local z_path
  z_path=$(z -l | fzf-tmux -d '100%' | awk '{print $2}')
  cd $(echo "$z_path")
}
zle     -N   fz
bindkey '^F' fz

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

export FZF_DEFAULT_OPTS='--border --height=60%'
export _Z_EXCLUDE_DIRS=".cache|.git|.venv|node_modules"
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow -g '!.git' -g '!node_modules' -g '!.venv' 2>/dev/null"

enable-fzf-tab
zstyle ':fzf-tab:*' fzf-pad 4

# SSH Agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# X
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
