on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@just

      - name: install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install Ansible
        run: just setup

      - name: Run ansible-lint
        run: .venv/bin/ansible-lint
